enabling interrupts
enableErrorInterrupt
	self setErrorInterruptEnableBit: 0;
		setErrorInterruptEnableBit: 1;
		setErrorInterruptEnableBit: 2;
		setErrorInterruptEnableBit: 3;
		setErrorInterruptEnableBit: 4;
		setErrorInterruptEnableBit: 5;
		setErrorInterruptStatusEnableBit: 1;
		setErrorInterruptStatusEnableBit: 2;
		setErrorInterruptStatusEnableBit: 3;
		setErrorInterruptStatusEnableBit: 4;
		setErrorInterruptStatusEnableBit: 5